USE [master]
GO
/****** Object:  Database [QLNSLC]    Script Date: 5/29/2024 2:29:57 PM ******/
CREATE DATABASE [QLNSLC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLNSLC', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLNSLC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLNSLC_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLNSLC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QLNSLC] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLNSLC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLNSLC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLNSLC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLNSLC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLNSLC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLNSLC] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLNSLC] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QLNSLC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLNSLC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLNSLC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLNSLC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLNSLC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLNSLC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLNSLC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLNSLC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLNSLC] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLNSLC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLNSLC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLNSLC] SET TRUSTWORTHY ON 
GO
ALTER DATABASE [QLNSLC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLNSLC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLNSLC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLNSLC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLNSLC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QLNSLC] SET  MULTI_USER 
GO
ALTER DATABASE [QLNSLC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLNSLC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLNSLC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLNSLC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLNSLC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLNSLC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QLNSLC] SET QUERY_STORE = OFF
GO
USE [QLNSLC]
GO
/****** Object:  Table [dbo].[CHUC_VU]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHUC_VU](
	[MACV] [varchar](10) NOT NULL,
	[TEN_CV] [nvarchar](50) NULL,
	[PHU_CAP] [decimal](10, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MACV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DAN_TOC]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DAN_TOC](
	[MADT] [smallint] IDENTITY(1,1) NOT NULL,
	[TEN_DT] [nvarchar](30) NULL,
	[PHU_CAP] [decimal](10, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MADT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HO_SO]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HO_SO](
	[MAHS] [varchar](10) NOT NULL,
	[HO] [nvarchar](30) NOT NULL,
	[TEN] [nvarchar](10) NOT NULL,
	[GIOI_TINH] [bit] NULL,
	[NGAY_SINH] [datetime] NULL,
	[NOI_SINH] [nvarchar](30) NULL,
	[HO_KHAU] [nvarchar](200) NULL,
	[DC_LIEN_HE] [nvarchar](200) NULL,
	[CMND] [varchar](12) NULL,
	[DANTOC] [smallint] NULL,
	[TONGIAO] [smallint] NULL,
	[SO_DT] [varchar](15) NULL,
	[EMAIL] [varchar](50) NULL,
	[NGOAI_NGU] [nvarchar](50) NULL,
	[TRINH_DO_HV] [tinyint] NULL,
	[GHI_CHU] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOC_VAN]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOC_VAN](
	[MAHV] [tinyint] IDENTITY(1,1) NOT NULL,
	[TENHV] [nvarchar](30) NULL,
	[CHUYEN_NGANH] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LUONG]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LUONG](
	[BACLUONG] [smallint] IDENTITY(1,1) NOT NULL,
	[LUONG_CO_BAN] [decimal](10, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BACLUONG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAN_VIEN]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAN_VIEN](
	[MANV] [varchar](10) NOT NULL,
	[MAHS] [varchar](10) NULL,
	[NGAY_VAO_LAM] [datetime] NULL,
	[TINH_TRANG] [tinyint] NULL,
	[MAT_KHAU] [varchar](50) NULL,
	[LOAI_NV] [tinyint] NULL,
	[LA_ADMIN] [bit] NULL,
	[PHONG] [varchar](10) NULL,
	[CHUCVU] [varchar](10) NULL,
	[BAC_LUONG] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHONG_BAN]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONG_BAN](
	[MAPB] [varchar](10) NOT NULL,
	[TEN_PB] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAPB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUAN_HE_GIA_DINH]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUAN_HE_GIA_DINH](
	[MAQHGD] [int] IDENTITY(1,1) NOT NULL,
	[MAHS] [varchar](10) NULL,
	[HOTEN] [nvarchar](50) NULL,
	[QUAN_HE] [nvarchar](10) NULL,
	[NAM_SINH] [varchar](4) NULL,
	[NGHE_NGHIEP] [nvarchar](50) NULL,
	[GIOI_TINH] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[MAQHGD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SO_CMND]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SO_CMND](
	[CMND] [varchar](12) NOT NULL,
	[NGAY_CAP] [datetime] NULL,
	[NOI_CAP] [nvarchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[CMND] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TON_GIAO]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TON_GIAO](
	[MATG] [smallint] IDENTITY(1,1) NOT NULL,
	[TEN_TG] [nvarchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[MATG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HO_SO]  WITH CHECK ADD FOREIGN KEY([CMND])
REFERENCES [dbo].[SO_CMND] ([CMND])
GO
ALTER TABLE [dbo].[HO_SO]  WITH CHECK ADD FOREIGN KEY([DANTOC])
REFERENCES [dbo].[DAN_TOC] ([MADT])
GO
ALTER TABLE [dbo].[HO_SO]  WITH CHECK ADD FOREIGN KEY([TONGIAO])
REFERENCES [dbo].[TON_GIAO] ([MATG])
GO
ALTER TABLE [dbo].[HO_SO]  WITH CHECK ADD FOREIGN KEY([TRINH_DO_HV])
REFERENCES [dbo].[HOC_VAN] ([MAHV])
GO
ALTER TABLE [dbo].[NHAN_VIEN]  WITH CHECK ADD FOREIGN KEY([BAC_LUONG])
REFERENCES [dbo].[LUONG] ([BACLUONG])
GO
ALTER TABLE [dbo].[NHAN_VIEN]  WITH CHECK ADD FOREIGN KEY([CHUCVU])
REFERENCES [dbo].[CHUC_VU] ([MACV])
GO
ALTER TABLE [dbo].[NHAN_VIEN]  WITH CHECK ADD FOREIGN KEY([MAHS])
REFERENCES [dbo].[HO_SO] ([MAHS])
GO
ALTER TABLE [dbo].[NHAN_VIEN]  WITH CHECK ADD FOREIGN KEY([PHONG])
REFERENCES [dbo].[PHONG_BAN] ([MAPB])
GO
ALTER TABLE [dbo].[QUAN_HE_GIA_DINH]  WITH CHECK ADD FOREIGN KEY([MAHS])
REFERENCES [dbo].[HO_SO] ([MAHS])
GO
/****** Object:  StoredProcedure [dbo].[EditCMND]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[EditCMND](
	@CMNDCU varchar(12),
	@CMND varchar(12),
	@NGAY_CAP datetime,
	@NOI_CAP nvarchar(30),
	@MaHS varchar(10)
)
as
begin
update HO_SO set CMND='' where MAHS=@MaHS
if @CMNDCU<>''
begin
update SO_CMND set CMND=@CMND, NGAY_CAP=@NGAY_CAP,NOI_CAP=@NOI_CAP where CMND=@CMNDCU
end
else
begin
	insert into SO_CMND values(@CMND,@NGAY_CAP,@NOI_CAP)
end
update HO_SO set CMND=@CMND where MAHS=@MaHS

end
GO
/****** Object:  StoredProcedure [dbo].[InsertDanToc]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[InsertDanToc]
(
	@TEN_DT NVARCHAR(30),
	@PHU_CAP DECIMAL(10,0)
)
AS
BEGIN
	
	INSERT INTO DAN_TOC VALUES(@TEN_DT,@PHU_CAP)
	
	SELECT @@IDENTITY
END
GO
/****** Object:  StoredProcedure [dbo].[InsertHocVan]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[InsertHocVan](
	@TENHV nvarchar(30),
	@CHUYEN_NGANH nvarchar(100)
)
as
begin
	INSERT INTO HOC_VAN VALUES(@TENHV,@CHUYEN_NGANH)
	
	SELECT @@IDENTITY
end
GO
/****** Object:  StoredProcedure [dbo].[InsertHoSoNV]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[InsertHoSoNV](
	@HO nvarchar(30),
	@TEN nvarchar(10),
	@GIOI_TINH bit,
	@NGAY_SINH datetime,
	@NOI_SINH nvarchar(30),
	@HO_KHAU nvarchar(200),
	@DC_LIEN_HE nvarchar(200),
	@CMND varchar(12),
	@DANTOC smallint,
	@TONGIAO smallint,
	@SO_DT varchar(15),
	@EMAIL varchar(50),
	@NGOAI_NGU nvarchar(50),
	@TRINH_DO_HV tinyint,
	@GHI_CHU nvarchar(100),
	@MANV varchar(10),
	@NGAY_VAO_LAM datetime,
	@TINH_TRANG tinyint,
	@LOAI_NV tinyint,
	@LA_ADMIN bit,
	@PHONG varchar(10),
	@CHUCVU varchar(10),
	@BAC_LUONG smallint
)
as
begin
	declare @MAHS varchar(10)
	set @MAHS=(SELECT MAX(MAHS) FROM HO_SO)
	
	DECLARE @SOHS INT
	SET @SOHS=CAST(SUBSTRING(@MAHS,3,LEN(@MAHS)) AS INT)+1
	
	IF @SOHS<10
	SET @MAHS='HS0000'+CAST(@SOHS AS CHAR(1))
	ELSE
	IF @SOHS<100
	SET @MAHS='HS000'+CAST(@SOHS AS CHAR(2))
	ELSE
	IF @SOHS<1000
	SET @MAHS='HS00'+CAST(@SOHS AS CHAR(3))
	ELSE
	IF @SOHS<10000
	SET @MAHS='HS0'+CAST(@SOHS AS CHAR(4))
	ELSE
	SET @MAHS='HS'+CAST(@SOHS AS VARCHAR(8))
	
	INSERT INTO HO_SO VALUES(@MAHS,@HO,@TEN,@GIOI_TINH,@NGAY_SINH,@NOI_SINH,@HO_KHAU,@DC_LIEN_HE,@CMND,@DANTOC,@TONGIAO,@SO_DT,@EMAIL,@NGOAI_NGU,@TRINH_DO_HV,@GHI_CHU)
	
	INSERT INTO NHAN_VIEN VALUES(@MANV,@MAHS,@NGAY_VAO_LAM,@TINH_TRANG,'123456',@LOAI_NV,@LA_ADMIN,@PHONG,@CHUCVU,@BAC_LUONG)
	
	SELECT @MAHS
	
end
GO
/****** Object:  StoredProcedure [dbo].[InsertLuong]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[InsertLuong](
	@LUONG_CO_BAN decimal(10,0)
)
as
begin
	INSERT INTO LUONG VALUES(@LUONG_CO_BAN)
	
	SELECT @@IDENTITY
end
GO
/****** Object:  StoredProcedure [dbo].[InsertThanNhan]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[InsertThanNhan](
	@MAHS varchar(10),
	@HOTEN nvarchar(50),
	@QUAN_HE nvarchar(10),
	@NAM_SINH varchar(4),
	@NGHE_NGHIEP nvarchar(50),
	@GIOI_TINH bit
)
as
begin
	INSERT INTO QUAN_HE_GIA_DINH VALUES(@MAHS,@HOTEN,@QUAN_HE,@NAM_SINH,@NGHE_NGHIEP,@GIOI_TINH)
	
	SELECT @@IDENTITY
end
GO
/****** Object:  StoredProcedure [dbo].[InsertTonGiao]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[InsertTonGiao]
(
	@TEN_TG NVARCHAR(30)
)
AS
BEGIN
	
	INSERT INTO TON_GIAO VALUES(@TEN_TG)
	
	SELECT @@IDENTITY
END
GO
/****** Object:  StoredProcedure [dbo].[SpLogin]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SpLogin]
(
	@MANV VARCHAR(10),
	@MATKHAU VARCHAR(50)	
)
AS
SELECT NHAN_VIEN.MANV,HO_SO.HO,HO_SO.TEN,NHAN_VIEN.LA_ADMIN FROM NHAN_VIEN
INNER JOIN HO_SO ON NHAN_VIEN.MAHS=HO_SO.MAHS
WHERE NHAN_VIEN.MANV=@MANV AND NHAN_VIEN.MAT_KHAU=@MATKHAU
GO
/****** Object:  StoredProcedure [dbo].[TESTCONNECTION]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[TESTCONNECTION]
AS
BEGIN
	declare @result bit
	set @result=0
	IF object_id('NHAN_VIEN') is not null
		if object_id('CHUC_VU') is not null
		if object_id('DAN_TOC') is not null
		if object_id('HO_SO') is not null
		if object_id('LUONG') is not null
		if object_id('HOC_VAN') is not null
		if object_id('PHONG_BAN') is not null
		if object_id('QUAN_HE_GIA_DINH') is not null
		if object_id('SO_CMND') is not null
		if object_id('TON_GIAO') is not null
		set @result=1
	select @result
END
GO
/****** Object:  StoredProcedure [dbo].[UpdateNV]    Script Date: 5/29/2024 2:29:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[UpdateNV](
	@HO nvarchar(30),
	@TEN nvarchar(10),
	@GIOI_TINH bit,
	@NGAY_SINH datetime,
	@NOI_SINH nvarchar(30),
	@HO_KHAU nvarchar(200),
	@DC_LIEN_HE nvarchar(200),
	@DANTOC smallint,
	@TONGIAO smallint,
	@SO_DT varchar(15),
	@EMAIL varchar(50),
	@NGOAI_NGU nvarchar(50),
	@TRINH_DO_HV tinyint,
	@GHI_CHU nvarchar(100),
	@MANV varchar(10),
	@NGAY_VAO_LAM datetime,
	@TINH_TRANG tinyint,
	@LOAI_NV tinyint,
	@LA_ADMIN bit,
	@PHONG varchar(10),
	@CHUCVU varchar(10),
	@BAC_LUONG smallint,
	@MAHS varchar(10)
)
as
begin
	
	update HO_SO set HO=@HO,TEN=@TEN,GIOI_TINH=@GIOI_TINH,NGAY_SINH=@NGAY_SINH,NOI_SINH=@NOI_SINH,HO_KHAU=@HO_KHAU,
	DC_LIEN_HE=@DC_LIEN_HE,DANTOC=@DANTOC,TONGIAO=@TONGIAO,SO_DT=@SO_DT,EMAIL=@EMAIL,NGOAI_NGU=@NGOAI_NGU,
	TRINH_DO_HV=@TRINH_DO_HV,GHI_CHU=@GHI_CHU WHERE MAHS=@MAHS
	
	UPDATE NHAN_VIEN SET NGAY_VAO_LAM=@NGAY_VAO_LAM,@TINH_TRANG=@TINH_TRANG,LOAI_NV=@LOAI_NV,LA_ADMIN=@LA_ADMIN,
	PHONG=@PHONG,CHUCVU=@CHUCVU,BAC_LUONG=@BAC_LUONG WHERE MANV=@MANV
end
GO
USE [master]
GO
ALTER DATABASE [QLNSLC] SET  READ_WRITE 
GO
